import type { Metadata } from "next";
import "./globals.css";
import BootstrapClient from "@/components/lib/BootstrapClient";
import Header from "@/components/layout/Header";
import NextProgressBar from "@/components/lib/NextNprogressBar";
import Toastify from "@/components/lib/Toastify";
import Footer from "@/components/layout/Footer";
import { Suspense } from "react";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Nextjs Ecommerce Foodie",
  description: "Generated by create next app for Foodie Ecommerce",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Suspense>
          <AuthProvider>
            <NextProgressBar>
              <Header />

              {children}

              <Footer />
              <Toastify />
              <BootstrapClient />
            </NextProgressBar>
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
