import type { Metadata } from "next";
import "./globals.css";
import BootstrapClient from "@/components/lib/BootstrapClient";
import Header from "@/components/layout/Header";


export const metadata: Metadata = {
  title: "Nextjs Ecommerce Foodie",
  description: "Generated by create next app for Foodie Ecommerce",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Header />

        {children}

        <BootstrapClient />
      </body>
    </html>
  );
}
